[build]
  base = "/"
  command = "pnpm install && pnpm turbo run build --filter=@myglambeauty/web"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://mini-ecommerce-software.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
